### ISSUE TITLE
Scaling issue in home page

### ISSUE THREAD

**Issue by TooniSkyy** [Kevinwochan/Nord-Google-Chrome-Chromium#1]
There is scaling issue in home page background picture. Im using 3840x2160res on 150% txt scale

![background](https://user-images.githubusercontent.com/48853617/59157139-35056780-8aae-11e9-8606-07003349fe4e.JPG)

**Comment by Kevinwochan** [comment]
I'm definitely not sure how to tackle this,
Google Chrome doesnt accept svg files, so any image i use won't scale responsively.

This is the best that i can do but it just doesnt look as good.
![image](https://user-images.githubusercontent.com/18486383/63174961-5b371d00-c086-11e9-8d18-74331ceeafbe.png)

If anyone that sees this is capable with adobe illustrator i'd love your help
