### ISSUE TITLE
My Issue is that this theme is the best Chromium theme out there 

### ISSUE THREAD

**Issue by charitarthchugh** [Kevinwochan/Nord-Google-Chrome-Chromium#3]
Just wanted to say thanks for this awesome theme!

**Comment by Kevinwochan** [comment]
aww you ❤️ that just made my day.

**Comment by charitarthchugh** [comment]
Is there a way to get this on the Nord Ports page? I would love to see this on there.

**Comment by Kevinwochan** [comment]
I submitted an Issue here https://github.com/arcticicestudio/nord/issues/116 but it seems they prioritise developer tools. 
Maybe one day 🤞
